### ISSUE TITLE
Rails-Recipe: Group RoR Capstone Project

### ISSUE THREAD

**Issue by mahdinoori2000** [mahdinoori2000/rails-recipe#11]
- [x] Here is the link to the project

https://github.com/mahdinoori2000/rails-recipe/projects/1

- [x] There are two people in this project:
[Mahdi Noori](https://github.com/mahdinoori2000)
[Alfred M.](https://github.com/badger-99)

**Comment by DammyShittu** [comment]
Hi @mahdinoori2000 and @badger-99,

## Highlights
✔️ Assigned and descriptive tasks

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Team member @mahdinoori2000 has a total of 7 tasks, which amounts to 21 points on the Kanban board, while @badger-99 has only 4 tasks which amounts to 8.5 points. Kindly reassign your tasks so that they are evenly distributed. No team member should have total points >= 5 more than the next team member.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DammyShittu** [comment]
Hi @mahdinoori2000 and @badger-99,

## APPROVED 🟢

## Highlights
✔️ Descriptive tasks

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
